// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddItem: typeof import('./src/components/windows/AddItem.vue')['default']
    Checkbox: typeof import('./src/components/elements/Checkbox.vue')['default']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    Header: typeof import('./src/components/Header.vue')['default']
    Input: typeof import('./src/components/elements/Input.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    Positions: typeof import('./src/components/windows/Positions.vue')['default']
  }
}

export { }
